Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,9 +45,56 @@ jobs:
         set -ex
         source ${{ matrix.environment-variables }}
         make docker-test-integration
-    - name: Upload cAdvisor log file
-      uses: actions/upload-artifact@v1
-      if: failure()
-      with:
-        name: cadvisor.log
-        path: ${{ github.workspace }}/go/src/github.com/google/cadvisor/cadvisor.log
+#     - name: Upload cAdvisor log file
+#       uses: actions/upload-artifact@v1
+#       if: failure()
+#       with:
+#         name: cadvisor.log
+#         path: ${{ github.workspace }}/go/src/github.com/google/cadvisor/cadvisor.log
+    test-integration-s390x:
+      runs-on: ubuntu-18.04
+      name: Build on s390x
+      steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 1
+          path: go/src/github.com/google/cadvisor
+      - name: Enable running multiple architectures
+        run: |
+          sudo docker run --rm --privileged linuxkit/binfmt:4ea3b9b0938cbd19834c096aa31ff475cc75d281
+      - uses: uraimo/run-on-arch-action@v2.1.2
+        with:
+          architecture: s390x
+          distribution: ubuntu18.04
+          run: |
+            set -euo pipefail
+            apt-get update
+            apt-get install -y --no-install-recommends \
+            apt-transport-https \
+            ca-certificates \
+            socat \
+            curl \
+            gnupg2 \
+            software-properties-common \
+            lsb-release \
+            build-essential \
+            git \
+            sudo
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
+            add-apt-repository \
+               "deb [arch=s390x] https://download.docker.com/linux/ubuntu \
+               $(lsb_release -cs) stable"
+            apt-get update
+            apt-cache madison docker-ce
+            cat /usr/sbin/policy-rc.d 
+            printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
+            cat /usr/sbin/policy-rc.d 
+            export RUNLEVEL=1
+            apt-get install -y --no-install-recommends docker-ce=18.06.*
+            curl https://go.dev/dl/go1.18.linux-s390x.tar.gz -o /tmp/go.tar.gz
+            tar -C /usr/local -xzf /tmp/go.tar.gz
+            export PATH="$PATH":/usr/local/go/bin
+            set -x
+            cd $GITHUB_WORKSPACE/go/src/github.com/google/cadvisor && source build/config/plain.sh && make test-integration
+    
